Powerhistory fixes (#176)
* added PowerHistory for Enchantments

* WIP : History tester

* fixed cardId on name for enchantments

* Add tagchanges to Plain Aura and Enchant

* added PowerHistory for Enchantments

* added empty name instead of null

* Fix tag value

* kettle protocol String string

* Fix tag changes for enchantments with scripttags

* replaced CoreAi with BasicAi in netStandard

* basicAi

* namespace refactoring

* AdjAura and Enrage TagChanges

* Tag changes for cost effects

* Fix tag changes on setting base_health

* added constructor for powerEntityChoices

* added deckserializer & tests from hearthdb including license
added constructor for powerEntityChoices

* gameConfigBuilder & test

* added more tests for gameconfigbuilder

* Fix OneTurnEffect TagChanges (#174)

* added print to powerhistorychangeentity

* refactored readonly struct to class for consistency

* Add GameConfig.DrawWithRandom
Add Game.SetRandomSeed

* Fix [BOT_079] Faithful Lumi

* Fix [EX1_183] Gift of the Wild

* Fix EntityData.Reset()

* Add GameConfing.DrawWithRandom

* added PowerHistory for Enchantments

* WIP : History tester

* fixed cardId on name for enchantments

* Add tagchanges to Plain Aura and Enchant

* added empty name instead of null

* Fix tag value

* kettle protocol String string

* replaced CoreAi with BasicAi in netStandard

* basicAi

* namespace refactoring

* AdjAura and Enrage TagChanges

* Tag changes for cost effects

* Fix tag changes on setting base_health

* added constructor for powerEntityChoices

* added deckserializer & tests from hearthdb including license
added constructor for powerEntityChoices

* gameConfigBuilder & test

* added more tests for gameconfigbuilder

* added print to powerhistorychangeentity

* refactored readonly struct to class for consistency

* Add GameConfing.DrawWithRandom

* Fix EntityChange history

* Add ShowEntity on RemoveFromDeck

* Add Unknown.Clone()

* added nuget and appveyor stuff

* fix, error CS0642: Possible mistaken empty statement